# This is a basic workflow to help you get started with Actions

name: Register Leetcode Problem

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      title:
        description: 'title'     
        required: true
      url:
        description: 'url'     
        required: true
      content:
        description: 'content'  
        required: true

env:
  USER_NAME: ${{ secrets.USER_NAME }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  TITLE: ${{ github.event.inputs.title }}
  URL: ${{ github.event.inputs.url }}
  CONTENT: ${{ github.event.inputs.content }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git init
      - name: some_name
        run: |
          git status 
           
      - name: create new file
        run: |
          pwd
          ls -al
          tree
          mkdir '${{ env.TITLE }}'
          echo '${{ env.CONTENT }}' > '${{ env.TITLE }}'/readme.md
          touch '${{ env.TITLE }}'/readme.md
          pwd
          ls -al
          tree
          cat '${{ env.TITLE }}'/readme.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: main
          file_pattern: '*.md'
          tagging_message: ${{ env.URL }}
          push_options: '--force'

