# This is a basic workflow to help you get started with Actions

name: Register Leetcode Problem

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      title:
        description: 'title'     
        required: true
      url:
        description: 'url'     
        required: true
      content:
        description: 'content'  
        required: true

env:
  USER_NAME: ${{ secrets.USER_NAME }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_TOKEN: ${{ secrets.USER_TOKEN }}
  TITLE: ${{ github.event.inputs.title }}
  URL: ${{ github.event.inputs.url }}
  CONTENT: ${{ github.event.inputs.content }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: init 
        run: |
          git config --global url.https//${USER_NAME}:${USER_TOKEN}@github.com/.insteadOf https://github.com/
          rm -rf *
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.USER_TOKEN }}
          ref: ${{ github.head_ref }}
           
      - name: create new file
        run: |
          pwd
          ls -al
          tree
          mkdir '${{ env.TITLE }}'
          echo '${{ env.CONTENT }}' > '${{ env.TITLE }}'/readme.md
          touch '${{ env.TITLE }}'/readme.md
          pwd
          ls -al
          tree
          cat '${{ env.TITLE }}'/readme.md
          git config --global user.email ${{ env.USER_EMAIL }}
          git config --global user.name ${{ env.USER_NAME }} 
          
      - name: Add file & Commit & Push
        run: |
          git config --global user.email ${{ env.USER_EMAIL }}
          git config --global user.name ${{ env.USER_NAME }} 
          git config --global -l
          touch '${{ env.TITLE }}'/readme.md
          git commit -m '${{ env.URL }}'
          git push origin ${{ github.head_ref }}
